


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_user_email_update"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
 
  if old.email <> new.email then
    
    
    update public.profils
    set email_adress = new.email
    where id = new.id; 
    
  end if;
  
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_user_email_update"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."activites" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "type_location" "text",
    "location" "text",
    "date" timestamp without time zone,
    "group_id" "uuid"
);


ALTER TABLE "public"."activites" OWNER TO "postgres";


ALTER TABLE "public"."activites" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activites_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."activites_profil" (
    "id" bigint NOT NULL,
    "profil_id" "uuid" NOT NULL,
    "activites_id" bigint,
    "authorisation_status" "text",
    "participation_status" "text",
    "profil_status" "text"
);


ALTER TABLE "public"."activites_profil" OWNER TO "postgres";


ALTER TABLE "public"."activites_profil" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activites_profil_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."expenses" (
    "id" bigint NOT NULL,
    "article" "text" NOT NULL,
    "date" "date",
    "profil_id" "uuid" DEFAULT "gen_random_uuid"(),
    "group_id" "uuid" DEFAULT "gen_random_uuid"(),
    "expense_amount" numeric
);


ALTER TABLE "public"."expenses" OWNER TO "postgres";


ALTER TABLE "public"."expenses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."expenses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."expenses_profil" (
    "id" bigint NOT NULL,
    "profil_id" "uuid" DEFAULT "gen_random_uuid"(),
    "debt_amount" numeric,
    "expenses_id" bigint
);


ALTER TABLE "public"."expenses_profil" OWNER TO "postgres";


ALTER TABLE "public"."expenses_profil" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."expenses_profil_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."groups" (
    "name" "text" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."groups" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."memberships" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid",
    "profil_id" "uuid",
    "display_name" "text"
);


ALTER TABLE "public"."memberships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."model_task" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "frequency" "text",
    "profil_id_order" "uuid"[],
    "date_ancre" "text",
    "comments" "text",
    "group_id" "uuid"
);


ALTER TABLE "public"."model_task" OWNER TO "postgres";


ALTER TABLE "public"."model_task" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."model_task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profils" (
    "firstname" "text" NOT NULL,
    "lastname" "text",
    "email_adress" "text" NOT NULL,
    "photo" "text",
    "id" "uuid" NOT NULL,
    "nickname" "text"
);


ALTER TABLE "public"."profils" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."remboursement" (
    "id" bigint NOT NULL,
    "profil_indebted_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "status" "text",
    "debt_amount" numeric,
    "profil_creditor_id" "uuid",
    "group_id" "uuid"
);


ALTER TABLE "public"."remboursement" OWNER TO "postgres";


ALTER TABLE "public"."remboursement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."remboursement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" bigint NOT NULL,
    "model_task_id" bigint NOT NULL,
    "group_id" "uuid" DEFAULT "gen_random_uuid"(),
    "status" boolean,
    "profil_id" "uuid",
    "date_limite" "text",
    "fait_le" "text",
    "retard" boolean
);


ALTER TABLE "public"."tasks" OWNER TO "postgres";


ALTER TABLE "public"."tasks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tasks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."activites"
    ADD CONSTRAINT "activites_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."activites_profil"
    ADD CONSTRAINT "activites_profil_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."expenses"
    ADD CONSTRAINT "expenses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."expenses_profil"
    ADD CONSTRAINT "expenses_profil_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."groups"
    ADD CONSTRAINT "groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."memberships"
    ADD CONSTRAINT "memberships_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."model_task"
    ADD CONSTRAINT "model_task_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profils"
    ADD CONSTRAINT "profils_email_adress_key" UNIQUE ("email_adress");



ALTER TABLE ONLY "public"."profils"
    ADD CONSTRAINT "profils_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."remboursement"
    ADD CONSTRAINT "remboursement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."activites"
    ADD CONSTRAINT "activites_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."activites_profil"
    ADD CONSTRAINT "activites_profil_activites_id_fkey" FOREIGN KEY ("activites_id") REFERENCES "public"."activites"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."activites_profil"
    ADD CONSTRAINT "activites_profil_profil_id_fkey" FOREIGN KEY ("profil_id") REFERENCES "public"."profils"("id");



ALTER TABLE ONLY "public"."expenses"
    ADD CONSTRAINT "expenses_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."expenses_profil"
    ADD CONSTRAINT "expenses_profil_expenses_id_fkey" FOREIGN KEY ("expenses_id") REFERENCES "public"."expenses"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."expenses"
    ADD CONSTRAINT "expenses_profil_id_fkey" FOREIGN KEY ("profil_id") REFERENCES "public"."profils"("id");



ALTER TABLE ONLY "public"."expenses_profil"
    ADD CONSTRAINT "expenses_profil_profil_id_fkey" FOREIGN KEY ("profil_id") REFERENCES "public"."profils"("id");



ALTER TABLE ONLY "public"."memberships"
    ADD CONSTRAINT "memberships_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."memberships"
    ADD CONSTRAINT "memberships_profil_id_fkey" FOREIGN KEY ("profil_id") REFERENCES "public"."profils"("id");



ALTER TABLE ONLY "public"."model_task"
    ADD CONSTRAINT "model_task_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."remboursement"
    ADD CONSTRAINT "remboursement_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."remboursement"
    ADD CONSTRAINT "remboursement_profil_creditor_id_fkey" FOREIGN KEY ("profil_creditor_id") REFERENCES "public"."profils"("id");



ALTER TABLE ONLY "public"."remboursement"
    ADD CONSTRAINT "remboursement_profil_indebted_id_fkey" FOREIGN KEY ("profil_indebted_id") REFERENCES "public"."profils"("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_model_task_id_fkey" FOREIGN KEY ("model_task_id") REFERENCES "public"."model_task"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_profil_id_fkey" FOREIGN KEY ("profil_id") REFERENCES "public"."profils"("id");



CREATE POLICY "Autoriser la lecture des profils" ON "public"."profils" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."activites" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."activites_profil" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."expenses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."expenses_profil" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."model_task" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profils" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."remboursement" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";








GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT ALL ON FUNCTION "public"."handle_user_email_update"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_user_email_update"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_user_email_update"() TO "service_role";
























GRANT ALL ON TABLE "public"."activites" TO "anon";
GRANT ALL ON TABLE "public"."activites" TO "authenticated";
GRANT ALL ON TABLE "public"."activites" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activites_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activites_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activites_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."activites_profil" TO "anon";
GRANT ALL ON TABLE "public"."activites_profil" TO "authenticated";
GRANT ALL ON TABLE "public"."activites_profil" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activites_profil_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activites_profil_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activites_profil_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."expenses" TO "anon";
GRANT ALL ON TABLE "public"."expenses" TO "authenticated";
GRANT ALL ON TABLE "public"."expenses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."expenses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."expenses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."expenses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."expenses_profil" TO "anon";
GRANT ALL ON TABLE "public"."expenses_profil" TO "authenticated";
GRANT ALL ON TABLE "public"."expenses_profil" TO "service_role";



GRANT ALL ON SEQUENCE "public"."expenses_profil_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."expenses_profil_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."expenses_profil_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."groups" TO "anon";
GRANT ALL ON TABLE "public"."groups" TO "authenticated";
GRANT ALL ON TABLE "public"."groups" TO "service_role";



GRANT ALL ON TABLE "public"."memberships" TO "anon";
GRANT ALL ON TABLE "public"."memberships" TO "authenticated";
GRANT ALL ON TABLE "public"."memberships" TO "service_role";



GRANT ALL ON TABLE "public"."model_task" TO "anon";
GRANT ALL ON TABLE "public"."model_task" TO "authenticated";
GRANT ALL ON TABLE "public"."model_task" TO "service_role";



GRANT ALL ON SEQUENCE "public"."model_task_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."model_task_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."model_task_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profils" TO "anon";
GRANT ALL ON TABLE "public"."profils" TO "authenticated";
GRANT ALL ON TABLE "public"."profils" TO "service_role";



GRANT ALL ON TABLE "public"."remboursement" TO "anon";
GRANT ALL ON TABLE "public"."remboursement" TO "authenticated";
GRANT ALL ON TABLE "public"."remboursement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."remboursement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."remboursement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."remboursement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tasks" TO "anon";
GRANT ALL ON TABLE "public"."tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tasks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tasks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tasks_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































